### ISSUE TITLE
【依頼】フリマアプリ挙動確認	

### ISSUE THREAD

**Issue by moritakayukihiro** [jenifa-moritakakun/furima-35570#9]
#フリマアプリのURL
https://furima-35570.herokuapp.com/

#Basic認証のIDとパスワード
ID: admin    パスワード: 2222

#出品者用のメールアドレスとパスワード
メールアドレス: yukihiro@yukihiro     パスワード: yukihiro1368

#購入者用のメールアドレスとパスワード
メールアドレス: ayaka@ayaka     パスワード: ayaka1368

**Comment by takumi0530** [comment]
@jenifa-moritakakun さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

### **[修正依頼箇所]**

- [x] **「画像/価格/商品名/配送料負担」の4つの情報について表示できていること**
配送料負担が数字に置き換わっています。
<img width="302" alt="スクリーンショット 2021-06-03 17 46 20" src="https://user-images.githubusercontent.com/76197191/120616121-e9ff6e80-c493-11eb-8603-360d267488ca.png">

- [x] **エラーハンドリングができていること（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）**
都道府県を入力せずに購入を押しても、エラーメッセージが出力されませんでした。

- [x] **クレジットカード決済ができること**
情報を入力しても、エラーメッセージが出て決済できませんでした。
**※上記により、購入機能と売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。**
<img width="450" alt="スクリーンショット 2021-06-03 17 53 55" src="https://user-images.githubusercontent.com/76197191/120617019-af4a0600-c494-11eb-85bf-da2f73ab089d.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、前回からの修正が確認できませんでした。
マージやデプロイ忘れの可能性もございますので、再度ご確認お願いいたします。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
ご提出ありがとうございます！

> ・「画像/価格/商品名/配送料負担」の4つの情報について表示できていること
> ・エラーハンドリングができていること（入力に問題がある状態で「購入」ボタンが押された場合、情報は受け入れられず、購入ページでエラーメッセージが表示されること）

こちらについては修正が確認できました🎉

引き続き以下のご確認をお願いします！

[修正依頼箇所]

- [x] **クレジットカード決済ができるようにしましょう**

以下のカード情報を入力しても購入ができませんでした。
```
・カード番号：4242424242424242
・有効期限：3月 23年
・セキュリティコード：123
```
※上記により、購入機能と売却後の動作確認ができておりません。次回ご提出時に確認させていただきます。
修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by takumi0530** [comment]
@jenifa-moritakakun さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
これからもスタッフ一同応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/76197191/120756551-58066d00-c54a-11eb-82e4-ddd23972ea73.png)
